<?php
$handleTable = new handleTable($config['database']['localhost'], $config['database']['dbname'], $config['database']['username'], $config['database']['password']);

// create table
// subkey, int, bigint, var, text, mediumtext, longtext, boolean

$handleTable->setCreateTableSql("table_album", ["id_list|int", "noibat|boolean", "type|var", "photo|var", "thumb|var", "ten_vi|var", "ten_en|var", "tenkhongdau|var", "title|var", "keywords|var", "description|var", "mota_vi|text", "mota_en|text", "noidung_vi|text", "noidung_en|text", "stt|int", "hienthi|boolean", "ngaytao|int", "ngaysua|int"]);
$handleTable->setCreateTableSql("table_album_photo", ["id_baiviet|int", "type|var", "photo|var", "thumb|var", "ten|var", "mota|var", "stt|int", "hienthi|boolean", "ngaytao|int", "ngaysua|int"]);
$handleTable->setCreateTableSql("table_alias", ["id_parent|int", "com|var", "act|var", "type|var", "tenkhongdau_vi|var", "tenkhongdau_en|var", "ngaytao|int", "ngaysua|int"]);
$handleTable->setCreateTableSql("table_attribute", ["ten_vi|var", "ten_en|var", "masp|var", "tragop|int",  "photo|var", "thumb|var", "giaban|int", "giacu|int", "status|int", "stt|int",  "type|var", "ngaytao|int", "ngaysua|int", "hienthi|boolean"]);
$handleTable->setCreateTableSql("table_baiviet", ["index_robots|var", "id_tacgia|int", "schema|var", "cano_vi|text", "cano_en|text", "id_list|int", "id_cat|int", "id_item|int", "id_sub|int", "id_product_list|text", "options|text", "noibat|boolean", "footer|boolean", "type|var", "photo|var", "photo2|text", "video|text", "iframe_map|text", "thumb|var", "ten_vi|var", "diachi_vi|var", "diachi_en|var", "tenkhongdau_vi|var", "tenkhongdau_en|var", "title_sub_vi|var", "title_sub_en|var", "mota_vi|longtext", "noidung_vi|longtext", "ten_en|var", "mota_en|longtext", "noidung_en|longtext", "stt|int", "hienthi|boolean", "ngaytao|int", "ngaysua|int", "luotxem|int", "thongtin_vi|text", "thongtin_en|text", "thongsokythuat_vi|text", "thongsokythuat_en|text", "huongdansudung_vi|text", "huongdansudung_en|text", "khuyenmai_vi|text", "khuyenmai_en|text", "tags|text", "tagskhongdau|text", "id_loai|int", "giaban|bigint", "giacu|int", "giabansale|int", "giasi|int", "masp|var", "id_thuonghieu|text", "link|var", "links|var", "rating|int", "mucluc|boolean", "job_vi|var", "job_en|var", "status|var", "dmindex|boolean", "link_facebook|var", "link_instagram|var", "link_zalo|var", "link_twitter|var", "link_ggmap|var", "max|bigint", "min|bigint", "slogan|var", "icon|var", "banner|var", "phone|var", "completion_date|int", "brand|text", "text_new|var", "installment|int", "sale|int", "flashsale|int", "xang|var", "sokm|var", "sosan|var", "sobai|int", "sohocvien|int", "banchay|int", "news|int", "hot|boolean", "donvitinh|var", "noibat_list|int", "sophong|int", "songuoi|int", "sogiuongngu|int", "dientich|int", "product_type|text", "technology|var", "weight|var", "size|var", "capacity|var", "power|var", "door|var", "sonhatam|int", "link_video|var", "qty|int", "qty_start|int"]);
$handleTable->setCreateTableSql("table_baiviet_cat", ["id_list|int", "cano_vi|text", "cano_en|text", "options|text", "type|var", "ten_vi|var", "ten_en|var", "mota_vi|longtext", "mota_en|longtext", "noidung_vi|longtext", "noidung_en|longtext", "tenkhongdau_vi|var", "tenkhongdau_en|var", "photo|var", "thumb|var", "stt|int", "hienthi|boolean", "noibat|boolean", "menu|boolean", "mucluc|boolean", "ngaytao|int", "ngaysua|int"]);
$handleTable->setCreateTableSql("table_baiviet_item", ["id_list|int", "cano_vi|text", "cano_en|text", "id_cat|int", "options|text", "mucluc|boolean", "type|var", "ten_vi|var", "ten_en|var", "mota_vi|longtext", "mota_en|longtext", "noidung_vi|longtext", "noidung_en|longtext", "tenkhongdau_vi|var", "tenkhongdau_en|var", "photo|var", "thumb|var", "stt|int", "hienthi|boolean", "ngaytao|int", "ngaysua|int"]);
$handleTable->setCreateTableSql("table_baiviet_list", ["options|text", "cano_vi|text", "cano_en|text", "type|var", "ten_vi|var", "ten_en|var", "title_sub_vi|var", "title_sub_en|var", "mota_vi|longtext", "mota_en|longtext", "noidung_vi|longtext", "noidung_en|longtext", "tenkhongdau_vi|var", "tenkhongdau_en|var", "photo|var", "thumb|var", "stt|int", "hienthi|boolean", "ngaytao|int", "ngaysua|int", "noibat|boolean", "noibat_combo|boolean", "icon|var", "banner|var", "banner_thumb|var", "icon_thumb|var", "menu|boolean", "mucluc|boolean", "footer|int", "link|var", "trend|boolean", "hot|boolean"]);
$handleTable->setCreateTableSql("table_baiviet_photo", ["id_baiviet|int", "id_product|int", "type|var", "photo|var", "thumb|var", "ten|var", "mota|var", "stt|int", "hienthi|boolean", "ngaytao|int", "ngaysua|int"]);
$handleTable->setCreateTableSql("table_baiviet_photo_properties", ["photo|var", "thumb|var", "id_product|int", "type|var", "ngaytao|int", "author_id|int", "hienthi|boolean", "stt|int"]);
$handleTable->setCreateTableSql("table_baiviet_properties", ["id_product|int", "ten_vi|var", "ten_en|var", "price|int", "qty|int", "photo|var", "thumb|var", "colors|var", "ngaytao|int", "ngaysua|int", "stt|int", "hienthi|boolean", "edit_count|int", "tenkhongdau_vi|var", "tenkhongdau_en|var", "author_id|int", "type|var"]);
$handleTable->setCreateTableSql("table_baiviet_sub", ["id_list|int", "id_cat|int", "id_item|int", "options|text", "type|var", "ten_vi|var", "ten_en|var", "mota_vi|longtext", "mota_en|longtext", "noidung_vi|longtext", "noidung_en|longtext", "tenkhongdau_vi|var", "tenkhongdau_en|var", "photo|var", "thumb|var", "stt|int", "hienthi|boolean", "noibat|boolean", "ngaytao|int", "ngaysua|int"]);
$handleTable->setCreateTableSql("table_bannerqc", ["stt|int", "options|var", "ten_vi|var", "ten_en|var", "slogan_vi|var", "slogan_en|var", "photo|var", "thumb|var", "link|var", "time_out|int", "count|int", "mota_vi|text", "mota_en|text", "type|var", "hienthi|boolean", "ngaytao|int", "ngaysua|int"]);
$handleTable->setCreateTableSql("table_booking", ["id_product|int", "ten_vi|var", "email|var", "dienthoai|text", "noidung|text", "diachi|text", "id_dichvu|int", "photo|var", "thumb|var", "type|var", "hienthi|boolean", "ngaytao|int", "ngaysua|int", "stt|int", "view|boolean", "gioitinh|var", "nhucau|var", "loai_sp|var", "ngaydatlich|var", "khunggio|var", "ngayvao|int", "ngayra|int", "sophong|int", "giaphong|int", "songuoi|int", "product|var", "loai_thung|var", "soluong|int", "quycach|var", "id_mxh|int", "website|var", "question1|text", "question2|text", "question3|text", "question4|text", "question5|text"]);
$handleTable->setCreateTableSql("table_combo", ["stt|int", "id_product|text", "ten_vi|var", "ten_en|var", "code|var", "type|var", "hienthi|boolean", "ngaytao|int", "ngaysua|int", "price|int", "photo|var", "thumb|var"]);
$handleTable->setCreateTableSql("table_comment", ["pid|int", "userid|int", "hoten|var", "diachi|var", "dienthoai|var", "email|var", "ngaytao|int", "ngaydanhgia|int", "content|text", "stt|int", "hienthi|boolean", "view|boolean", "rating|int", "cauhoi|var", "traloi|var", "ip|int", "browser|var", "url|var", "type|var", "admin|boolean", "photo|var"]);
$handleTable->setCreateTableSql("table_company", ["type|var", "ten_vi|var", "tenkhongdau|var", "mota_vi|longtext", "noidung_vi|longtext", "ten_en|var", "mota_en|longtext", "noidung_en|longtext", "title|var", "keywords|var", "description|var", "photo|var", "thumb|var", "stt|int", "hienthi|boolean", "ngaytao|int", "ngaysua|int"]);
$handleTable->setCreateTableSql("table_contact", ["fullname|var", "email|var", "address|var", "phone|var", "subject|var", "content|text", "notes|text", "view|boolean", "status|var", "edit_count|int", "createdAt|int", "updatedAt|int", "type|var", "author_id|int", "stt|int", "hienthi|boolean", "photo|var", "thumb|var"]);
$handleTable->setCreateTableSql("table_counters", ["tm|int", "ip|var", "browser|var", "pageview|boolean", "device|var", "nation|var", "fromto|var", "osdetail|var", "website|var", "os|var", "dateupdate|datetime", "type|var"]);
$handleTable->setCreateTableSql("table_coupons", ["code|var", "start_date|int", "end_date|int", "qty|int", "numb|int", "status|var", "createdAt|int", "updatedAt|int", "price_start|int", "price|int", "price_end|int", "percents|float", "edit_count|int", "author_id|int"]);
$handleTable->setCreateTableSql("table_customers", ["confirm_code|var", "fullname|var", "username|var", "email|var", "phone|var", "address|var", "gender|int", "birthday|var", "id_city|int", "id_dist|int", "id_ward|int", "password|var", "userid|var", "photo|var", "thumb|var", "status|var", "secret|var", "activation|var", "edit_count|int", "numb|int", "createdAt|int", "updatedAt|int", "type|var", "author_id|int", "id_google|var", "firstname|var", "lastname|var", "card|var", "issued|var", "date_of_issue|var", "address_current|var", "address_residential|var", "avatar|var", "before_card|var", "after_card|var", "bank_number|var", "bank_name|var", "bank_id|var", "bank_address|var", "flags|int", "member|var", "login_session|var", "lastlogin|int", "token|var", "hienthi|boolean"]);
$handleTable->setCreateTableSql("table_customer_address", ["id_user|int", "fullname|var", "phone|var", "address|var", "id_city|int", "id_dist|int", "id_ward|int", "type|var", "numb|int", "status|var", "createdAt|int", "updatedAt|int", "edit_count|int", "check_default|boolean"]);
$handleTable->setCreateTableSql("table_flashsale", ["ten_vi|longtext", "ten_en|longtext", "time_start|var", "time_end|var", "photo|text", "thumb|text", "hienthi|boolean", "ngaytao|var", "ngaysua|var", "stt|int", "id_product|var", "type|var"]);
$handleTable->setCreateTableSql("table_info", ["type|var", "ten_vi|var", "tenkhongdau_vi|var", "tenkhongdau_en|var", "mota_vi|longtext", "noidung_vi|longtext", "ten_en|var", "mota_en|longtext", "noidung_en|longtext", "title|var", "keywords|var", "description|var", "photo|var", "photo2|text", "thumb|var", "stt|int", "hienthi|boolean", "ngaytao|int", "ngaysua|int", "links|var", "slogan_vi|var", "slogan_en|var", "video|var", "link_type|int", "text_vi|var", "text_en|var", "mucluc|boolean"]);
$handleTable->setCreateTableSql("table_lang", ["item|var", "lang_vi|text", "lang_en|text"]);
$handleTable->setCreateTableSql("table_map", ["ten_vi|var", "ten_en|var", "tenkhongdau|var", "photo|var", "thumb|var", "stt|int", "hienthi|boolean", "ngaytao|int", "ngaysua|int", "diachi_vi|var", "dienthoai|var", "toado|var", "iframe_map|text", "email|var", "website|var", "diachi_en|var", "mota_vi|text", "mota_en|text", "noidung_vi|text", "noidung_en|text", "text_search|var", "timework|int", "phone|var", "mocua|var", "type|var"]);
$handleTable->setCreateTableSql("table_newsletter", ["ten_vi|var", "ngayhen|var", "thumb|var", "photo|var", "file|var", "email|var", "dienthoai|text", "chude_vi|var", "noidung|text", "ghichu_vi|var", "tinhtrang|var", "diachi|text", "type|var", "hienthi|boolean", "ngaytao|int", "ngaysua|int", "stt|int"]);
$handleTable->setCreateTableSql("table_online", ["session_id|var", "time|int"]);
$handleTable->setCreateTableSql("table_order", ["id_customer|int", "code|var", "fullname|var", "email|var", "phone|var", "address|var", "id_city|int", "id_dist|int", "other_address|boolean", "email_other|var", "fullname_other|var", "phone_other|var", "address_other|var", "id_city_other|int", "id_dist_other|int", "total_price|int", "total_price_tmp|int", "sale_off|int", "view|boolean", "status|var", "order_status|int", "payment|int", "payship|int", "payment_status|int", "content|text", "notes|text", "edit_count|int", "createdAt|int", "updatedAt|int", "type|var", "author_id|int", "numb|int", "coupons|var", "coupon_percent|float", "body_carts|longtext", "body_codes|var", "body_checks|boolean", "id_combo|var", "total_combo|int"]);
$handleTable->setCreateTableSql("table_order_combo_detail", ["id_order|int", "id_product|int", "code|var", "name|var", "photo|var", "color|int", "size|int", "material|int", "qty|int", "price|int", "sale_off|int", "createdAt|int", "updatedAt|int", "product_detail|text"]);
$handleTable->setCreateTableSql("table_order_detail", ["id_order|int", "id_product|int", "code|var", "name|var", "photo|var", "color|int", "size|int", "material|int", "qty|int", "price|int", "sale_off|int", "options|text", "createdAt|int", "updatedAt|int"]);
$handleTable->setCreateTableSql("table_order_detail1", ["id_order|int", "id_product|int", "code|var", "name|var", "photo|var", "color|int", "size|int", "material|int", "qty|int", "price|int", "sale_off|int", "createdAt|int", "updatedAt|int"]);
$handleTable->setCreateTableSql("table_order_returns", ["id_order|int", "id_customer|int", "code|var", "total_price|int", "sale_off|int", "status|var", "edit_count|int", "createdAt|int", "updatedAt|int", "author_id|int"]);
$handleTable->setCreateTableSql("table_order_status", ["name_vi|var", "classname|var", "name_en|var"]);
$handleTable->setCreateTableSql("table_phanquyen", ["permission|int", "funtions|var"]);
$handleTable->setCreateTableSql("table_photo", ["photo|var", "thumb|var", "ten_vi|var", "ten_en|var", "link|var", "mota_vi|text", "mota_en|text", "stt|int", "hienthi|boolean", "type|var", "number|int", "ngaytao|int", "ngaysua|int", "slogan_vi|var", "check_video|int", "link_facebook|text", "link_twitter|text", "link_tiktok|text", "noibat|boolean", "video|var", "tieuchi|var", "slogan_en|var", "job_vi|var", "job_en|var", "phone|var", "zalo|var", "email|var", "address|var", "category_img|int", "link_video|var", "rating|int", "ngaysua|int"]);
$handleTable->setCreateTableSql("table_photo_attributes", ["id_product|int", "photo|var", "thumb|var", "stt|int", "ngaytao|int", "ngaysua|int", "type|var", "hienthi|boolean"]);
$handleTable->setCreateTableSql("table_place_citys", ["name_vi|var", "name_en|var", "alias_vi|var", "alias_en|var", "code|var", "createdAt|int", "updatedAt|int", "status|var", "numb|int"]);
$handleTable->setCreateTableSql("table_place_dists", ["id_city|int", "name_vi|var", "name_en|var", "alias_vi|var", "alias_en|var", "code|var", "createdAt|int", "updatedAt|int", "status|var", "numb|int"]);
$handleTable->setCreateTableSql("table_redirect", ["oldlink|var", "typelink|var", "newlink|var", "createAt|int", "updateAt|int"]);
$handleTable->setCreateTableSql("table_seo", ["idmuc|int", "com|var", "act|var", "title_vi|var", "keywords_vi|var", "description_vi|text", "title_en|var", "keywords_en|var", "description_en|text", "type|var", "schema|text"]);
$handleTable->setCreateTableSql("table_seopage", ["photo|var", "thumb|var", "options|var", "mota_vi|longtext", "mota_en|longtext", "noidung_vi|longtext", "noidung_en|longtext", "title_vi|var", "keywords_vi|var", "description_vi|var", "title_en|var", "keywords_en|var", "description_en|var", "type|var", "ngaytao|int", "ngaysua|int", "mucluc|boolean"]);
$handleTable->setCreateTableSql("table_setting", ["title|var", "keywords|var", "description|var", "photo|var", "name_vi|var", "name_en|var", "subject_vi|var", "subject_en|var", "slogan_vi|text", "slogan_en|text", "email|var", "dienthoai|var", "address_vi|var", "address_en|var", "lang_default|var", "options|text", "district|var", "city|var", "tax_code|var", "blank|var", "denominator|var", "symbol|var", "postalcode|var", "chinhanh_vi|var", "chinhanh_en|var", "hotline|var", "map_marker|text", "iframe_video|var", "iframe_map|text", "iframe_map1|mediumtext", "website|var", "faceid|var", "facebook|var", "facebook2|var", "analytics|text", "vchat|text", "code_body|text", "bgtop|var", "bgcontent|var", "tags|text", "tagskhongdau|text", "page_video|int", "hotlinepage|text", "lienketweb|text", "disable_web|boolean", "block_copy|boolean", "slider_web|int", "sozalo|var", "hotline_kinhdoanh|var", "hotline_kythuat|var", "linkmessage|var", "linksyoutube|var", "scrolltext1_vi|var", "scrolltext2_vi|var", "scrolltext1_en|var", "scrolltext2_en|var", "dola|float", "yen|float", "tiente|float", "copyright_vi|var", "copyright_en|var", "slider_video|int", "mastertool|var", "seo|var", "timework_vi|var", "timework_en|var", "time_start|int", "time_end|int", "counter|var", "ngaysua|int", "time_slider|int", "sharelink|text", "time_popup|int"]);
$handleTable->setCreateTableSql("table_tags", ["options|var", "ten_vi|var", "cano_vi|var", "cano_en|text", "ten_en|var", "tenkhongdau_vi|var", "tenkhongdau_en|var", "mota_vi|text", "noidung_vi|longtext", "noidung_en|longtext", "mota_en|text", "photo|var", "thumb|var", "title|var", "keywords|var", "description|text", "ngaytao|int", "ngaysua|int", "type|var", "hienthi|boolean", "stt|int"]);
$handleTable->setCreateTableSql("table_user", ["username|var", "password|var", "ten|var", "dienthoai|var", "email|var", "diachi|var", "sex|boolean", "nick_yahoo|var", "nick_skype|var", "congty|var", "country|var", "city|var", "quyen|var", "role|boolean", "hienthi|boolean", "com|var", "type|var", "stt|int", "permission|var", "login_session|var", "last_login|int", "user_token|var", "lastlogin|var", "avatar|var", "ngaytao|int", "ngaysua|int"]);
$handleTable->setCreateTableSql("table_user_limit", ["login_ip|var", "login_attempts|int", "attempt_time|int", "locked_time|int"]);
$handleTable->setCreateTableSql("table_user_log", ["id_user|int", "ip|var", "timelog|int", "user_agent|text"]);
$handleTable->setCreateTableSql("table_video", ["id_list|int", "noibat|boolean", "type|var", "photo|var", "thumb|var", "video|var", "ten_vi|var", "tenkhongdau|var", "links|var", "title|var", "keywords|var", "description|var", "ten_en|var", "stt|int", "hienthi|boolean", "ngaytao|int", "ngaysua|int", "luotxem|int", "mota_en|text", "mota_vi|text"]);

// insert table
// $handleTable->setInsertTableSql("table_aaa", array(
//     ["text", "54222", "3123213"],
//     ["text", "54222", "3123dsadasa213"],
//     ["text", "54222", "31232dsadsa13"],
//     ["text", "54222", "312dsadsad3213", "54222", "312dsadsad3213"],
//     ["text", "54222", "3123dsadsa213", "54222", "312dsdấdsadsaddadsad3213"],
//     ["text", "54222", "312dsad3213", "54222", "312dsasddsasdadadasdadadaddsad3213", "54222", "312dsadsad3213"],
// ));

// truncate table
// $handleTable->setTruncateTableSql("table_aaa");
// $handleTable->setTruncateTableSql("table_aadsada");

// khởi động hàm
// $handleTable->autoHandleTable();
