<?php 
@define ('_sua','Sửa');
@define ('_bancomuonxoa','Bạn có muốn xóa');
@define ('_hocvien','Học viên');
@define ('_baihoc','Bài học');
@define ('_khuyenmai','Khuyến Mãi');
@define ('_xemtatcasanpham','Xem thêm');
@define ('_danhmucnoibat','Danh Mục Nổi Bật ');
@define ('_timhieuthem','Tìm Hiểu Thêm');
@define ('_giay','Giây');
@define ('_phut','Phút');
@define ('_gio','Giờ');
@define ('_ngay','Ngày');
@define ('_themvaogiohang','Thêm Vào Giỏ hàng');
@define ('_luotmua','Lượt mua');
@define ('_ngonngu','Ngôn ngữ');
@define ('_cauhinhchung','Cấu hình chung');
@define ('_baiviet','Bài viết');
@define ('_thongbaodangnhap','Tài khoản của bạn đã hết hạn đăng nhập hoặc đã đăng nhập trên thiết bị khác');
@define ('_trangkhongtontai','Trang không tồn tại');
@define ('_chiase','Chia sẻ');
@define ('_hienthithem','HIển thị thêm');
@define ('_tienganh','Tiếng Anh');
@define ('_tiengviet','Tiếng Việt');
@define ('_chiduong','Chỉ đường');
@define ('_dong','Đóng');
@define ('_tendathaydoihoactamthoikhongkhadung','Tên đã thay đổi hoặc tạm thời không khả dụng');
@define ('_xinloinhungtrangbandangtimkiemkhongtontaihoacdabixoa','Xin lỗi nhưng trang bạn đang tìm kiếm không tồn tại hoặc đã bị xóa');
@define ('_trangcuabankhongduoctimthay','Trang của bạn không được tìm thấy');
@define ('_vetrangchu','Về trang chủ');
@define ('_chuacodonhangdethanhtoan','Chưa có đơn hàng để thanh toán...');
@define ('_khongcosanphamnaotronggio','Không có sản phẩm nào trong giỏ');
@define ('_tieptucmuahang','Tiếp tục mua hàng');
@define ('_chungtoiselienhelaivoibandexacnhanvayeucaugiaohang','Chúng tôi sẽ liên hệ lại với bạn để xác nhận và yêu cầu giao hàng');
@define ('_donhangcuabanseduocxulytrongthoigiansomnhat','Đơn hàng của bạn sẽ được xử lý trong thời gian sớm nhất');
@define ('_camonbandadathang','Cảm ơn bạn đã đặt hàng');
@define ('_moithacmacxinvuilonglienhe','Mọi thắc mắc xin vui lòng liên hệ');
@define ('_thongtinchitietseduocguidenhopthucuaban','Thông tin chi tiết sẽ được gửi đến hộp thư của bạn');
@define ('_hientaidonhangdangduocxuly','Hiện tại đơn hàng đang được xử lý');
@define ('_madonhangcuabanla','Mã đơn hàng của bạn là');
@define ('_dathangthanhcong','Đặt hàng thành công');
@define ('_xacnhan','Xác nhận');
@define ('_trolai','Trở lại');
@define ('_thoathuan','Thỏa thuận');
@define ('_phivanchuyen','Phí vận chuyển');
@define ('_chiphihanghoa','Chi phí hàng hóa');
@define ('_xacnhanthanhtoan','Xác nhận thanh toán');
@define ('_dongia','Đơn giá');
@define ('_ghichu','Ghi chú');
@define ('_chonquanhuyen','Chọn quận huyện');
@define ('_thanhtoandonhang','Thanh toán đơn hàng');
@define ('_dabaogomvatneuco','Đã bao gồm VAT nếu có');
@define ('_hoantat','Hoàn tất');
@define ('_giaohangthanhtoan','Giao hàng thanh toán');
@define ('_khongtimthayketqua','Không tìm thấy kết quả');
@define ('_chiase','Chia sẻ');
@define ('_chinhsach','Chính sách');
@define ('_tamhethang','Tạm hết hàng');
@define ('_conhang','Còn hàng');
@define ('_masanpham','Mã sản phẩm');
@define ('_danhgia','Đánh giá');
@define ('_noidungdangcapnhat','Nội dung đang cập nhật...');
@define ('_gia','Giá');
@define ('_muangay','Mua ngay');
@define ('_sanphamlienquan','Sản phẩm liên quan');
@define ('_chitietsanpham','Chi tiết sản phẩm');
@define ('_lienhevoichungtoi','Liên hệ với chúng tôi');
@define ('_nhapsodienthoai','Nhập số điện thoại');
@define ('_yeucaugoilai','Yêu cầu gọi lại');
@define ('_baivietlienquan','Bài viết liên quan');
@define ('_guithongtin','Gửi thông tin');
@define ('_mabaomat','Mã bảo mật');
@define ('_guithudenchungtoi','Gửi thư đến chúng tôi');
@define ('_lienhe','Liên hệ');
@define ('_timhieuthem','Tìm hiểu thêm');
@define ('_luotxem','Lượt xem');
@define ('_xemtatca','Xem tất cả');
@define ('_khoanggia','Khoảng giá');
@define ('_thuonghieu','Thương hiệu');
@define ('_thanhcong','Thành công');
@define ('_thanhtoan','Thanh toán');
@define ('_timkiem','Tìm kiếm');
@define ('_tacgia','Tác giả');
@define ('_khuyenmaidanhchoban','Khuyến mãi dành cho bạn');
@define ('_themvaogio','Thêm vào giỏ');
@define ('_sanphamnoibat','Sản phẩm nổi bật');
@define ('_xuhuongtimkiem','Xu hướng tìm kiếm');
@define ('_xemngay','Xem ngay');
@define ('_baivietmoinhat','Bài viết mới nhất');
@define ('_nam','Năm');
@define ('_thang','Tháng');
@define ('_ngay','Ngày');
@define ('_xemthem','Xem thêm');
@define ('_nhapemailcuaban','Nhập email của bạn');
@define ('_dangkynhantin','Đăng ký nhận tin');
@define ('_ketnoivoichungtoi','Kết nối với chúng tôi');
@define ('_dangky','Đăng ký');
@define ('_quydinhvachinhsach','Quy định & Chính sách');
@define ('_hotrokhachhang','Hỗ trợ khách hàng');
@define ('_ve','Về');
@define ('_thongtinlienhe','Thông tin liên hệ');
@define ('_lienhe','Liên hệ');
@define ('_tintuc','Tin tức');
@define ('_duan','Dự án');
@define ('_dichvu','Dịch vụ');
@define ('_sanpham','Sản phẩm');
@define ('_gioithieu','Giới thiệu');
@define ('_trangchu','Trang chủ');
@define ('_giohang','Giỏ hàng');
@define ('_giaidaphotrongaytucthi','Giải đáp hỗ trợ ngay tức thì');
@define ('_chatfacebook','Chat facebook');
@define ('_chatzalo','Chat zalo');
@define ('_danhmuc','Danh mục');
@define ('_thanhtoan','Thanh toán');
@define ('_tamtinh','Tạm tính');
@define ('_phuongthucgiaohang','Phương thức giao hàng');
@define ('_phuongthucthanhtoan','Phương thức thanh toán');
@define ('_chontinhthanh','Chọn tỉnh thành');
@define ('_tinhtrang','Tình trạng');
@define ('_thanhtien','Thành tiền');
@define ('_soluong','Số lượng');
@define ('_tongdonhang','Tổng đơn hàng');
@define ('_tensanpham','Tên sản phẩm');
@define ('_yeucauthem','Yêu cầu thêm');
@define ('_quanhuyen','Quận huyện');
@define ('_tinhthanh','Tỉnh thành');
@define ('_thongtinnguoimua','Thông tin người mua');
@define ('_thongtindonhang','Thông tin đơn hàng');
@define ('_xemvasuadonhang','Xem và sửa đơn hàng');
@define ('_ngaydat','Ngày đặt');
@define ('_hoten','Họ tên');
@define ('_tim','Tìm');
@define ('_sodienthoai','Số điện thoại');
@define ('_hovaten','Họ và tên');
@define ('_hovaten','Họ và tên');
@define ('_madonhang','Mã đơn hàng');
@define ('_donhang','Đơn hàng');
@define ('_them','Thêm');
@define ('_quanlylienhe','Quản lý liên hệ');
@define ('_cauhinhwebsite','Cấu hình website');
@define ('_thietlaphethong','Thiết lập hệ thống');
@define ('_danhsach','Danh sách');
@define ('_update','Cập nhật');
@define ('_tatca','Tất cả');
@define ('_hethongcuahang','Hệ thống cửa hàng');
@define ('_laymanhung','Lấy mã nhúng');
@define ('_noidung','Nội dung');
@define ('_kytu','Ký tự');
@define ('_thuoctinh','Thuộc tính');
@define ('_thongtin','Thông tin');
@define ('_tendanhmuc','Tên danh mục');
@define ('_thutu','Thứ tự');
@define ('_uploadhinhanh','Upload hình ảnh');
@define ('_anhien','Ẩn hiện');
@define ('_hinhanh','Hình ảnh');
@define ('_stt','Stt');
@define ('_ngaytao','Ngày tạo');
@define ('_ten','Tên');
@define ('_sothutu','Stt');
@define ('_mota','Mô tả');
@define ('_diachi','Địa chỉ');
@define ('_email','Email');
@define ('_dienthoai','Điện thoại');
@define ('_sozalo','Số zalo');
@define ('_website','Website');
@define ('_linkmessage','Link message');
@define ('_toadoweb','Tạo độ website');
@define ('_nhungiframe','Nhúng iframe');
@define ('_codebody','Code body');
@define ('_codehead','Code header');
@define ('_tieude','Tiêu đề');
@define ('_noidungseo','Nội dung seo');
@define ('_thuoctinhcauhinh','Thuộc tính cấu hình');
@define ('_thongtinchung','Thông tin chung');
@define ('_thaotac','Thao tác');
@define ('_tenbien','Tên biến');
?>